#ifndef MIDI_MAPPING_H
#define MIDI_MAPPING_H

#define MIDI_TRACK1_REC 10
#define MIDI_TRACK1_PLAY 20
#define MIDI_TRACK1_EN 30
#define MIDI_TRACK1_FX_SELECTOR 40
#define MIDI_TRACK1_FX_TWEAK 50
#define MIDI_TRACK1_REVERSE 60

#define MIDI_TRACK2_REC 11
#define MIDI_TRACK2_PLAY 21
#define MIDI_TRACK2_EN 31
#define MIDI_TRACK2_FX_SELECTOR 41
#define MIDI_TRACK2_FX_TWEAK 51
#define MIDI_TRACK2_REVERSE 61

#define MIDI_TRACK3_REC 12
#define MIDI_TRACK3_PLAY 22
#define MIDI_TRACK3_EN 32
#define MIDI_TRACK3_FX_SELECTOR 42
#define MIDI_TRACK3_FX_TWEAK 52
#define MIDI_TRACK3_REVERSE 62

#define MIDI_TRACK4_REC 13
#define MIDI_TRACK4_PLAY 23
#define MIDI_TRACK4_EN 33
#define MIDI_TRACK4_FX_SELECTOR 43
#define MIDI_TRACK4_FX_TWEAK 53
#define MIDI_TRACK4_REVERSE 63

#define MIDI_TRANSPORT_PLAY 1
#define MIDI_TRANSPORT_STOP 2
#define MIDI_TRANSPORT_METRONOME 3
#define MIDI_TRANSPORT_TEMPO 5

#endif
