
#define PIN_TRACK1_REC_BTN A9
#define PIN_TRACK1_REC_LED 4
#define PIN_TRACK1_EN_BTN A4
#define PIN_TRACK1_EN_LED 9

#define PIN_TRACK2_REC_BTN A8
#define PIN_TRACK2_REC_LED 5
#define PIN_TRACK2_EN_BTN A3
#define PIN_TRACK2_EN_LED 10

#define PIN_TRACK3_REC_BTN A7
#define PIN_TRACK3_REC_LED 6
#define PIN_TRACK3_EN_BTN A2
#define PIN_TRACK3_EN_LED 11

#define PIN_TRACK4_REC_BTN A6
#define PIN_TRACK4_REC_LED 7
#define PIN_TRACK4_EN_BTN A1
#define PIN_TRACK4_EN_LED 12

#define PIN_TRACK1_FX_SEL_CLK 32
#define PIN_TRACK1_FX_SEL_DT 30
#define PIN_TRACK1_FX_SEL_BTN 28

#define PIN_TRACK2_FX_SEL_CLK 33
#define PIN_TRACK2_FX_SEL_DT 31
#define PIN_TRACK2_FX_SEL_BTN 29

#define PIN_TRACK3_FX_SEL_CLK 44
#define PIN_TRACK3_FX_SEL_DT 42
#define PIN_TRACK3_FX_SEL_BTN 40

#define PIN_TRACK4_FX_SEL_CLK 45
#define PIN_TRACK4_FX_SEL_DT 43
#define PIN_TRACK4_FX_SEL_BTN 41


#define PIN_TRACK1_FX_PAR_CLK 27
#define PIN_TRACK1_FX_PAR_DT 25
#define PIN_TRACK1_FX_PAR_BTN 23

#define PIN_TRACK2_FX_PAR_CLK 38
#define PIN_TRACK2_FX_PAR_DT 36
#define PIN_TRACK2_FX_PAR_BTN 34

#define PIN_TRACK3_FX_PAR_CLK 39
#define PIN_TRACK3_FX_PAR_DT 37
#define PIN_TRACK3_FX_PAR_BTN 35

#define PIN_TRACK4_FX_PAR_CLK 50
#define PIN_TRACK4_FX_PAR_DT 48
#define PIN_TRACK4_FX_PAR_BTN 46

#define PIN_TEMPO_CLK 26
#define PIN_TEMPO_DT 24
#define PIN_TEMPO_BTN 22

#define PIN_NEOPIXEL_CONSOLE 14
#define PIN_NEOPIXEL_BOX 15

#define MIDI_TRACK1_REC 10
#define MIDI_TRACK1_PLAY 20
#define MIDI_TRACK1_EN 30
#define MIDI_TRACK1_FX_SELECTOR 40
#define MIDI_TRACK1_FX_TWEAK 50

#define MIDI_TRACK2_REC 11
#define MIDI_TRACK2_PLAY 21
#define MIDI_TRACK2_EN 31
#define MIDI_TRACK2_FX_SELECTOR 41
#define MIDI_TRACK2_FX_TWEAK 51

#define MIDI_TRACK3_REC 12
#define MIDI_TRACK3_PLAY 22
#define MIDI_TRACK3_EN 32
#define MIDI_TRACK3_FX_SELECTOR 42
#define MIDI_TRACK3_FX_TWEAK 52

#define MIDI_TRACK4_REC 13
#define MIDI_TRACK4_PLAY 23
#define MIDI_TRACK4_EN 33
#define MIDI_TRACK4_FX_SELECTOR 43
#define MIDI_TRACK4_FX_TWEAK 53

#define MIDI_TRANSPORT_PLAY 1
#define MIDI_TRANSPORT_STOP 2
#define MIDI_TRANSPORT_METRONOME 3
#define MIDI_TRANSPORT_TEMPO 5
