
#define PIN_TRACK1_REC_BTN 9 //A9
#define PIN_TRACK1_REC_LED 8
#define PIN_TRACK1_EN_BTN 7
#define PIN_TRACK1_EN_LED 6

#define PIN_TRACK2_REC_BTN 13 //A9
#define PIN_TRACK2_REC_LED 4
#define PIN_TRACK2_EN_BTN A5
#define PIN_TRACK2_EN_LED 8

#define PIN_TRACK3_REC_BTN 13 //A9
#define PIN_TRACK3_REC_LED 4
#define PIN_TRACK3_EN_BTN A5
#define PIN_TRACK3_EN_LED 8

#define PIN_TRACK4_REC_BTN 13 //A9
#define PIN_TRACK4_REC_LED 4
#define PIN_TRACK4_EN_BTN A5
#define PIN_TRACK4_EN_LED 8

#define PIN_NEOPIXEL_CONSOLE 2
#define PIN_NEOPIXEL_BOX 1

#define MIDI_TRACK1_REC 10
#define MIDI_TRACK1_PLAY 20
#define MIDI_TRACK1_EN 30
#define MIDI_TRACK1_FX_SELECTOR 40
#define MIDI_TRACK1_FX_TWEAK 50

#define MIDI_TRACK2_REC 11
#define MIDI_TRACK2_PLAY 21
#define MIDI_TRACK2_EN 31
#define MIDI_TRACK2_FX_SELECTOR 41
#define MIDI_TRACK2_FX_TWEAK 51

#define MIDI_TRACK3_REC 12
#define MIDI_TRACK3_PLAY 22
#define MIDI_TRACK3_EN 32
#define MIDI_TRACK3_FX_SELECTOR 42
#define MIDI_TRACK3_FX_TWEAK 52

#define MIDI_TRACK4_REC 13
#define MIDI_TRACK4_PLAY 23
#define MIDI_TRACK4_EN 33
#define MIDI_TRACK4_FX_SELECTOR 43
#define MIDI_TRACK4_FX_TWEAK 53

#define MIDI_TRANSPORT_PLAY 1
#define MIDI_TRANSPORT_STOP 2
#define MIDI_TRANSPORT_METRONOME 3
#define MIDI_TRANSPORT_TEMPO 5
